FROM mcr.microsoft.com/dotnet/sdk:5.0-focal AS build
WORKDIR /src

COPY ["tests/Tests.csproj", "tests/"]
COPY ["src/Domain/Domain.csproj", "src/Domain/"]
WORKDIR /src/tests
RUN dotnet restore "Tests.csproj"
COPY tests .

WORKDIR /src/tests
RUN dotnet build "Tests.csproj"
ENTRYPOINT ["dotnet", "test"]
