FROM mcr.microsoft.com/dotnet/sdk:5.0-focal AS build
WORKDIR /src

COPY ["src/Domain/", "src/Domain/"]
COPY ["tests/", "tests/"]

WORKDIR /src/tests
RUN dotnet restore "Tests.csproj"
RUN dotnet build "Tests.csproj"
ENTRYPOINT ["dotnet", "test"]
