// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServiceTemplate.DataAccess.Contexts;

namespace DataAccess.Migrations
{
    [DbContext(typeof(CoinsContext))]
    [Migration("20220216172618_Nullable.")]
    partial class Nullable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("ServiceTemplate.DataAccess.Entities.CoinCount", b =>
                {
                    b.Property<uint>("Denominator")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Count")
                        .HasColumnType("INTEGER");

                    b.HasKey("Denominator");

                    b.ToTable("Coins");
                });
#pragma warning restore 612, 618
        }
    }
}
