name: Docker Image CI

on:
  push:
    branches: [ magister ]
  pull_request:
    branches: [ magister ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag digitalthinks:$(date +%s)
      working-directory: src
